[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/rk-food-backend-1.0.0.jar"
healthcheckPath = "/api/products"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "production"
